/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client_gui;

/**
 *
 * @author rahulthawal
 */
public class Client_Run extends javax.swing.JFrame {

    /**
     * Creates new form C_GUI
     */
    public Client_Run() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PROJECT_LABEL = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JButton();
        register = new javax.swing.JButton();
        operations = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        BANKING_LABEL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CLIENT");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PROJECT_LABEL.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        PROJECT_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        PROJECT_LABEL.setText("Project based on PKI Infrastructure.");
        getContentPane().add(PROJECT_LABEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 12, 395, 51));

        login.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        register.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        register.setText("REGISTER");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        operations.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        operations.setText("OPERATIONS");
        operations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operationsActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        logout.setText("LOGOUT");

        BANKING_LABEL.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        BANKING_LABEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BANKING_LABEL.setText("Banking Operations");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BANKING_LABEL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(register)
                        .addGap(30, 30, 30)
                        .addComponent(login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(operations)
                        .addGap(18, 18, 18)
                        .addComponent(logout)
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(BANKING_LABEL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout)
                    .addComponent(operations)
                    .addComponent(login)
                    .addComponent(register))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 81, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        
        // CODE TO HANDLE FOR REGISTRATION PURPOSE.
        
        Register_GUI i1 = new Register_GUI();
        i1.setVisible(rootPaneCheckingEnabled);
        
    }//GEN-LAST:event_registerActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        
        Login_page login = new Login_page();
        login.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_loginActionPerformed

    private void operationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operationsActionPerformed
        // TODO add your handling code here:
        Operations bo = new Operations();
        
        
        
        bo.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_operationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                Login_page abc = new Login_page();
                         
                               
                //if(abc.msg(equals("abc")))            
              //  {
               //     new C_GUI().setVisible(true);
               // }
                                 
                
                new Client_Run().setVisible(true);
                
                
                
                
            }

            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel BANKING_LABEL;
    public javax.swing.JLabel PROJECT_LABEL;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JButton login;
    public javax.swing.JButton logout;
    public static javax.swing.JButton operations;
    public javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
