
package client_gui;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author rahulthawal
 */
public class Register_GUI extends javax.swing.JFrame {

    
    public Register_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitbutton = new javax.swing.JButton();
        USERNAME_LABEL = new javax.swing.JLabel();
        PASSWORD_LABEL = new javax.swing.JLabel();
        RETYPEPASSWORD_LABEl = new javax.swing.JLabel();
        clickregister = new javax.swing.JButton();
        UserName = new javax.swing.JTextField();
        PassWord = new javax.swing.JPasswordField();
        RetypePassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTER_FORM");

        exitbutton.setText("EXIT");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        USERNAME_LABEL.setText("USERNAME");

        PASSWORD_LABEL.setText("PASSWORD");

        RETYPEPASSWORD_LABEl.setText("RETYPE PASSWORD");

        clickregister.setText("REGISTER");
        clickregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickregisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(RETYPEPASSWORD_LABEl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(USERNAME_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PASSWORD_LABEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(exitbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PassWord)
                    .addComponent(UserName)
                    .addComponent(RetypePassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(clickregister)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(USERNAME_LABEL)
                    .addComponent(UserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PASSWORD_LABEL)
                    .addComponent(PassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RETYPEPASSWORD_LABEl)
                    .addComponent(RetypePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitbutton)
                    .addComponent(clickregister))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        // CODE TO EXIT THIS FRAME
        this.dispose();
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void clickregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickregisterActionPerformed
        // TODO add your handling code here:
       
        // CODE FOR REGISTRATION PROCESS 
        
	 String USERNAME = this.UserName.getText(); // To get the text values from username textfield
         String PASSWORD = this.PassWord.getText(); // To get the text values from password textfield
         String REPASSWORD = this.RetypePassword.getText(); // To get the text values from retypepassword textfield
         
         // To handle cases when there is no USERNAME
         if(USERNAME == null || USERNAME.trim().length() <= 0)
         {
		JOptionPane.showMessageDialog(this,"PLEASE ENTER VALID USERNAME");
		UserName.requestFocus();
		return;
	}
         // To handle cases when there is no PASSWORD
	if(PASSWORD == null || PASSWORD.trim().length() <= 0)
        {
		JOptionPane.showMessageDialog(this,"PLEASE ENTER PASSWORD");
		PassWord.requestFocus();
		return;
	}
	 // PASSWORD and REPASSWORD must be EQUAL
	if(!PASSWORD.equals(REPASSWORD))
        {
		JOptionPane.showMessageDialog(this,"MISMATCH PASSWORD");
		RetypePassword.requestFocus();
		return;
	}
	try
        {
		Socket socket = new Socket("localhost",1111); // Connecting to localhost having 1111 as port number.
                
		ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream());
                
		Object req[] = {"newuser",USERNAME,PASSWORD,REPASSWORD}; // Database consists of table newuser having username, password, confirm_password as fields 
                
		out.writeObject(req);   // write the object to stream
                
		out.flush(); // Flush the stream.
                
		ObjectInputStream in = new ObjectInputStream(socket.getInputStream());
		Object res[] = (Object[])in.readObject(); // reading object values from Stream.
		String response = (String)res[0];
		String msg[] = response.split(",");
                System.out.println(msg);
                
                // when new user has successfully completed creating account
		if(msg[0].equals("success"))
                {
			JOptionPane.showMessageDialog(this,"REGISTRATION COMPLETED. ACCOUNT NUMBER IS : "+msg[1]);
		}
                
                // To handle when user is failed to creare a account
                else
                {
			JOptionPane.showMessageDialog(this,"FAILED TO REGISTER");
		}
                
	}
        catch(Exception e)
        {
		e.printStackTrace();
	}
        
    }//GEN-LAST:event_clickregisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel PASSWORD_LABEL;
    public javax.swing.JPasswordField PassWord;
    public javax.swing.JLabel RETYPEPASSWORD_LABEl;
    public javax.swing.JPasswordField RetypePassword;
    public javax.swing.JLabel USERNAME_LABEL;
    public javax.swing.JTextField UserName;
    private javax.swing.JButton clickregister;
    private javax.swing.JButton exitbutton;
    // End of variables declaration//GEN-END:variables
}
